#!/usr/bin/env perl
use strict;
use warnings;

use Data::Dumper::Compact 'ddc';
use WebService::Clockify;

my $key  = shift || die "Usage: perl $0 apikey [stop]\n";
my $stop = shift || 0;

my $w = WebService::Clockify->new(apikey => $key);

my $r = $w->user;
#warn ddc($r); exit;

if ($stop) {
    $r = $w->stop_timer;
}
else {
    $r = $w->fetch(endpoint => 'projects');
    my $project_id = $r->[0]{id};

    $r = $w->fetch(endpoint => 'tags');
    my $tag_id = $r->[0]{id};

    $r = $w->start_timer({
        billable  => 1,
        projectId => $project_id,
        $tag_id ? (tagIds => [$tag_id]) : (),
    }) if $project_id;
}
warn ddc($r); exit;
